name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: npm install

      - name: Testes
        run: npm test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Railway login
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --api-token $RAILWAY_TOKEN
